### ISSUE TITLE
Minimum requirements not met

### ISSUE THREAD

**Issue by Shikeagle** [elisemercury/Duplicate-Image-Finder#70] opened 2023-03-26 13:28 UTC
Running dif.py where import packages are not found hard halts the program.  I am not sure if it is intentional, but running this without having say matplotlib installed in my case, throws a "ModuleNotFoundError" and stops the program.  Not sure if there is a more graceful way to handle missing requirements or not.  May want to consider adding any "non standard" modules to the documentation pages so that they can be downloaded before attempting usage.   If  these are in the documentation somewhere already, I apologize that I did not find it prior to posting this.

**Comment by elisemercury** [comment] 2023-03-26 22:33
Hi @Shikeagle,

Thanks for opening and flagging this issue! Indeed this is not intended behaviour, as difPy should automatically install all required dependencies during its installation. The issue has been fixed in version `v3.0.10`. 

Again thanks and best,
Elise

**Closed by elisemercury** 2023-03-26 22:33 UTC
Labels: bug : non-critical
