### ISSUE TITLE
Will not work in a script.

### ISSUE THREAD

**Issue by hesmith1029** [elisemercury/Duplicate-Image-Finder#97] opened 2024-06-08 19:46 UTC
If I run difPy examples from a Python Console it works.   If I put the same commands into a script (test.py) and issue a run command it fails.   I think the useful part of the error message that comes back is. 
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

        To fix this issue, refer to the "Safe importing of main module"
        section in https://docs.python.org/3/library/multiprocessing.html

I am using PyCharm 2024.1.2 (Community Edition),  python 3.12 on Windows 10.   I have tried putting the freeze_support into difPy in the  if__Name__ section of the library with no impact.  (It is my understanding that this section only runs if dif.py is called stand alone, and with my script that is not the case, so this solution not working is the expected result)

**Comment by hesmith1029** [comment] 2024-06-14 15:36
Found a work around.  Please close

**Comment by caniyabanci76** [comment] 2024-08-17 12:18
> Found a work around. Please close

An explanation of your workaround would be apprciated. Experiencing the same problem

**Comment by amalic** [comment] 2024-08-26 13:02
@hesmith1029 Any reason why you have not provided the solution to this problem?

**Comment by elisemercury** [comment] 2024-10-09 20:22
This is a duplicate of issue https://github.com/elisemercury/Duplicate-Image-Finder/issues/85. Please follow the updates there.

**Closed by elisemercury** 2024-10-09 20:22 UTC
