### ISSUE TITLE
Problem with multiprocessing

### ISSUE THREAD

**Issue by Bruce172** [elisemercury/Duplicate-Image-Finder#102] opened 2024-09-10 20:48 UTC
![Screenshot 2024-09-10 164552](https://github.com/user-attachments/assets/c00044ed-4bd6-458d-b113-f62b9f40ca90)

**Comment by elisemercury** [comment] 2024-10-09 20:21
This is a duplicate of issue #85. Please follow the updates there.

**Closed by elisemercury** 2024-10-09 20:21 UTC
Labels: duplicate
